<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Verify.Xunit" Version="26.2.0" />
        <PackageReference Include="Verify.SourceGenerators" Version="2.3.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.10.0" PrivateAssets="all" />
        <PackageReference Include="Basic.Reference.Assemblies" Version="1.7.2" />
    </ItemGroup>
</Project>
