//HintName: Derived.CachedPropertyInfo.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
public static class DerivedProps
{
    public static readonly global::PropertyCacheHelper.Shared.CachedPropertyInfo<global::Derived, int> IdDerived = new(x => x.IdDerived);
}
