<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <Compile Remove="Consumers/**/*.cs" />
        <None Include="Consumers/**/*" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SourceGenerator\AutoImplementedProperties.SourceGenerator.csproj"/>
    </ItemGroup>
</Project>
