//HintName: Hello`2.AutoProps.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
partial class Hello<TKey, TValue>
{
    public TKey Key { get; set; }
    public TValue Value { get; set; }
}
