using System;
using System.Threading;
using AutoImplementedProperties.Attributes;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AutoImplementedProperties.SourceGenerator;

public static class ShouldBeAutogened
{
    public readonly struct TypedGeneratorContext
    {
        public readonly INamedTypeSymbol TargetSymbol;
        public readonly TypeDeclarationSyntax TargetNode;
        public readonly SemanticModel SemanticModel;
        public readonly AutoImplementPropertiesAttribute Attribute;

        public TypedGeneratorContext(
            INamedTypeSymbol targetSymbol,
            TypeDeclarationSyntax targetNode,
            SemanticModel semanticModel,
            AutoImplementPropertiesAttribute attribute)
        {
            TargetSymbol = targetSymbol;
            TargetNode = targetNode;
            SemanticModel = semanticModel;
            Attribute = attribute;
        }
    }

    public static IncrementalValuesProvider<T> ForAutoImplementedAttribute<T>(
        this SyntaxValueProvider syntaxProvider,
        Func<TypedGeneratorContext, CancellationToken, T> valueFactory,
        Func<SyntaxNode, CancellationToken, bool>? additionalSyntaxFilter = null)
    {
        Func<SyntaxNode, CancellationToken, bool> filter;
        if (additionalSyntaxFilter == null)
        {
            filter = (node, token) => node is TypeDeclarationSyntax;
        }
        else
        {
            filter = (node, token) => node is TypeDeclarationSyntax
                && additionalSyntaxFilter(node, token);
        }

        return syntaxProvider.ForAttributeWithMetadataName(
            typeof(AutoImplementPropertiesAttribute).FullName
                ?? throw new InvalidOperationException("Attribute type without full name"),
            filter,
            (context, cancellationToken) =>
            {
                INamedTypeSymbol symbol = (INamedTypeSymbol) context.TargetSymbol;
                var attribute = GetAutoImplementPropertiesAttribute(context);
                var typedContext = new TypedGeneratorContext(
                    symbol,
                    (TypeDeclarationSyntax) context.TargetNode,
                    context.SemanticModel,
                    attribute);
                return valueFactory(typedContext, cancellationToken);
            });
    }

    // NOTE: should return an equivalent autogenerated type
    public static AutoImplementPropertiesAttribute GetAutoImplementPropertiesAttribute(
        this GeneratorAttributeSyntaxContext context)
    {
        var syntax = context.TargetNode as TypeDeclarationSyntax;
        return new AutoImplementPropertiesAttribute();
    }
}
