//HintName: Hello.CachedPropertyInfo.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
public static class HelloProps
{
    public static readonly global::CachedPropertyInfo.Shared.CachedPropertyInfo<global::Hello, int> Id = new(x => x.Id);
    public static readonly global::CachedPropertyInfo.Shared.CachedPropertyInfo<global::Hello, string?> Name = new(x => x.Name);
}
