//HintName: MyOtherResult.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
using ResultTypes.Shared;
using System;
public partial record struct MyOtherResult
{
    public required MyOtherResultTag Tag { get; init; }
    public global::System.Exception? Exception { get; init; }
    public MyOtherResultPayload Payload;
    public static MyOtherResult Ok(global::Payload1 payload)
    {
        var tag = global::WellKnownResult.Ok;
        return new()
        {
            Tag = new(tag),
            Payload = new()
            {
                Payload1 = payload,
            },
        };
    }

}
public partial record struct MyOtherResultTag
{
    public global::ResultBase Value { get; }
    public readonly bool IsNone => Value.IsNone;
    private MyOtherResultTag(global::ResultBase tag) => Value = tag;
    public MyOtherResultTag(global::WellKnownResult tag)
    {
        global::System.Diagnostics.Debug.Assert(tag is global::WellKnownResult.Ok);
        Value = global::ResultBase.Create<global::WellKnownResult>(tag);
    }

    public static MyOtherResultTag TryCreateWithCheck(global::ResultBase value)
    {
        var ret = new MyOtherResultTag(value);
        if (value.IsNone)
        {
            return ret;
        }
        {
            var r = ret.As<global::WellKnownResult>();
            if (r != (global::WellKnownResult) 0)
            {
                return ret;
            }
        }
        return new(global::ResultBase.None);
    }
    public static readonly global::System.Collections.Immutable.ImmutableArray<global::ResultSet> ResultSets = [
        global::ResultBase.ResultSetOf<global::WellKnownResult>([global::WellKnownResult.Ok]),
    ];
    public static void Declare()
    {
        global::ResultBase.Declare<global::WellKnownResult>();
    }
    public readonly global::WellKnownResult AsWellKnown()
    {
        return Value.As<global::WellKnownResult>();
    }

    public readonly T As<T>() where T : struct
    {
        if (typeof(T) == typeof(global::WellKnownResult))
        {
            return (T) (object) AsWellKnown();
        }
        throw new global::System.InvalidOperationException($"Type {typeof(T).FullName!} is not allowed here");
    }

    public readonly bool IsOk
    {
        get
        {
            {
                var r = As<global::WellKnownResult>();
                if (r != (global::WellKnownResult) 0)
                {
                    if (r == global::WellKnownResult.Ok)
                    {
                        return true;
                    }
                }
            }
            return false;
        }
    }
}
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Auto)]
public partial record struct MyOtherResultPayload
{
    public global::Payload1 Payload1;
}
