//HintName: MyResult.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
using ResultTypes.Shared;
using System;
public partial record struct MyResult
{
    public required MyResultTag Tag { get; init; }
    public global::System.Exception? Exception { get; init; }
    public MyResultPayload Payload;
    public static MyResult Failure(global::Tag1 tag, global::PayloadA payload, global::System.Exception? exception = null)
    {
        global::System.Diagnostics.Debug.Assert(tag is global::Tag1.A);
        return new()
        {
            Tag = new(tag),
            Payload = new()
            {
                PayloadA = payload,
            },
            Exception = exception,
        };
    }

}
public partial record struct MyResultTag
{
    public global::ResultBase Value { get; }
    public readonly bool IsNone => Value.IsNone;
    private MyResultTag(global::ResultBase tag) => Value = tag;
    public MyResultTag(global::Tag1 tag)
    {
        global::System.Diagnostics.Debug.Assert(tag is global::Tag1.A);
        Value = global::ResultBase.Create<global::Tag1>(tag);
    }

    public static MyResultTag TryCreateWithCheck(global::ResultBase value)
    {
        var ret = new MyResultTag(value);
        if (value.IsNone)
        {
            return ret;
        }
        {
            var r = ret.As<global::Tag1>();
            if (r != (global::Tag1) 0)
            {
                return ret;
            }
        }
        return new(global::ResultBase.None);
    }
    public static readonly global::System.Collections.Immutable.ImmutableArray<global::ResultSet> ResultSets = [
        global::ResultBase.ResultSetOf<global::Tag1>([global::Tag1.A]),
    ];
    public static void Declare()
    {
        global::ResultBase.Declare<global::Tag1>();
    }
    public readonly global::Tag1 AsTag1()
    {
        return Value.As<global::Tag1>();
    }

    public readonly T As<T>() where T : struct
    {
        if (typeof(T) == typeof(global::Tag1))
        {
            return (T) (object) AsTag1();
        }
        throw new global::System.InvalidOperationException($"Type {typeof(T).FullName!} is not allowed here");
    }

    public readonly bool IsOk
    {
        get
        {
            return false;
        }
    }
}
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Auto)]
public partial record struct MyResultPayload
{
    public global::PayloadA PayloadA;
}
