//HintName: MyResult.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
using ResultTypes.Shared;
using System;
public partial record struct MyResult
{
    public required MyResultTag Tag { get; init; }
    public global::System.Exception? Exception { get; init; }
    public MyResultPayload Payload => new();
    public static MyResult Ok(global::Tag tag)
    {
        global::System.Diagnostics.Debug.Assert(tag is global::Tag.A);
        return new()
        {
            Tag = new(tag),
        };
    }

    public static MyResult Failure(global::Tag tag, global::System.Exception? exception = null)
    {
        global::System.Diagnostics.Debug.Assert(tag is global::Tag.B);
        return new()
        {
            Tag = new(tag),
            Exception = exception,
        };
    }

}
public partial record struct MyResultTag
{
    public global::ResultBase Value { get; }
    public readonly bool IsNone => Value.IsNone;
    private MyResultTag(global::ResultBase tag) => Value = tag;
    public MyResultTag(global::Tag tag)
    {
        global::System.Diagnostics.Debug.Assert(tag is global::Tag.A or global::Tag.B);
        Value = global::ResultBase.Create<global::Tag>(tag);
    }

    public static MyResultTag TryCreateWithCheck(global::ResultBase value)
    {
        var ret = new MyResultTag(value);
        if (value.IsNone)
        {
            return ret;
        }
        {
            var r = ret.As<global::Tag>();
            if (r != (global::Tag) 0)
            {
                return ret;
            }
        }
        return new(global::ResultBase.None);
    }
    public static readonly global::System.Collections.Immutable.ImmutableArray<global::ResultSet> ResultSets = [
        global::ResultBase.ResultSetOf<global::Tag>([global::Tag.A, global::Tag.B]),
    ];
    public static void Declare()
    {
        global::ResultBase.Declare<global::Tag>();
    }
    public readonly global::Tag AsTag()
    {
        return Value.As<global::Tag>();
    }

    public readonly T As<T>() where T : struct
    {
        if (typeof(T) == typeof(global::Tag))
        {
            return (T) (object) AsTag();
        }
        throw new global::System.InvalidOperationException($"Type {typeof(T).FullName!} is not allowed here");
    }

    public readonly bool IsOk
    {
        get
        {
            {
                var r = As<global::Tag>();
                if (r != (global::Tag) 0)
                {
                    if (r == global::Tag.A)
                    {
                        return true;
                    }
                }
            }
            return false;
        }
    }
}
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Auto)]
public partial record struct MyResultPayload
{
}
