//HintName: MyOtherResult.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
using ResultTypes.Shared;
using System;
public partial record struct MyOtherResult
{
    public required MyOtherResultTag Tag { get; init; }
    public global::System.Exception? Exception { get; init; }
    public MyOtherResultPayload Payload;
    public static MyOtherResult Ok(global::Tag1 tag)
    {
        global::System.Diagnostics.Debug.Assert(tag is global::Tag1.A);
        return new()
        {
            Tag = new(tag),
        };
    }

    public static MyOtherResult Failure(global::Tag2 tag, global::Payload1 payload, global::System.Exception? exception = null)
    {
        global::System.Diagnostics.Debug.Assert(tag is global::Tag2.C);
        return new()
        {
            Tag = new(tag),
            Payload = new()
            {
                Payload1 = payload,
            },
            Exception = exception,
        };
    }

}
public partial record struct MyOtherResultTag
{
    public global::ResultBase Value { get; }
    public readonly bool IsNone => Value.IsNone;
    private MyOtherResultTag(global::ResultBase tag) => Value = tag;
    public MyOtherResultTag(global::Tag1 tag)
    {
        global::System.Diagnostics.Debug.Assert(tag is global::Tag1.A);
        Value = global::ResultBase.Create<global::Tag1>(tag);
    }

    public MyOtherResultTag(global::Tag2 tag)
    {
        global::System.Diagnostics.Debug.Assert(tag is global::Tag2.C);
        Value = global::ResultBase.Create<global::Tag2>(tag);
    }

    public static MyOtherResultTag TryCreateWithCheck(global::ResultBase value)
    {
        var ret = new MyOtherResultTag(value);
        if (value.IsNone)
        {
            return ret;
        }
        {
            var r = ret.As<global::Tag1>();
            if (r != (global::Tag1) 0)
            {
                return ret;
            }
        }
        {
            var r = ret.As<global::Tag2>();
            if (r != (global::Tag2) 0)
            {
                return ret;
            }
        }
        return new(global::ResultBase.None);
    }
    public static readonly global::System.Collections.Immutable.ImmutableArray<global::ResultSet> ResultSets = [
        global::ResultBase.ResultSetOf<global::Tag1>([global::Tag1.A]),
        global::ResultBase.ResultSetOf<global::Tag2>([global::Tag2.C]),
    ];
    public static void Declare()
    {
        global::ResultBase.Declare<global::Tag1>();
        global::ResultBase.Declare<global::Tag2>();
    }
    public readonly global::Tag1 AsTag1()
    {
        return Value.As<global::Tag1>();
    }

    public readonly global::Tag2 AsTag2()
    {
        return Value.As<global::Tag2>();
    }

    public readonly T As<T>() where T : struct
    {
        if (typeof(T) == typeof(global::Tag1))
        {
            return (T) (object) AsTag1();
        }
        if (typeof(T) == typeof(global::Tag2))
        {
            return (T) (object) AsTag2();
        }
        throw new global::System.InvalidOperationException($"Type {typeof(T).FullName!} is not allowed here");
    }

    public readonly bool IsOk
    {
        get
        {
            {
                var r = As<global::Tag1>();
                if (r != (global::Tag1) 0)
                {
                    if (r == global::Tag1.A)
                    {
                        return true;
                    }
                }
            }
            return false;
        }
    }
}
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Auto)]
public partial record struct MyOtherResultPayload
{
    public global::Payload1 Payload1;
}
