//HintName: Result.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
using ResultTypes.Shared;
using System;
partial class Helper0
{
    public partial record struct Result
    {
        public required ResultTag Tag { get; init; }
        public global::System.Exception? Exception { get; init; }
        public ResultPayload Payload => new();
        public static Result Ok(global::Result1 tag)
        {
            global::System.Diagnostics.Debug.Assert(tag is global::Result1.Hello or global::Result1.World);
            return new()
            {
                Tag = new(tag),
            };
        }

        public static Result Failure(global::System.Exception? exception = null)
        {
            var tag = global::WellKnownResult.GenericFailure;
            return new()
            {
                Tag = new(tag),
                Exception = exception,
            };
        }

    }
}
partial class Helper0
{
    public partial record struct ResultTag
    {
        public global::ResultBase Value { get; }
        public readonly bool IsNone => Value.IsNone;
        private ResultTag(global::ResultBase tag) => Value = tag;
        public ResultTag(global::Result1 tag)
        {
            global::System.Diagnostics.Debug.Assert(tag is global::Result1.Hello or global::Result1.World);
            Value = global::ResultBase.Create<global::Result1>(tag);
        }

        public ResultTag(global::WellKnownResult tag)
        {
            global::System.Diagnostics.Debug.Assert(tag is global::WellKnownResult.GenericFailure);
            Value = global::ResultBase.Create<global::WellKnownResult>(tag);
        }

        public static ResultTag TryCreateWithCheck(global::ResultBase value)
        {
            var ret = new ResultTag(value);
            if (value.IsNone)
            {
                return ret;
            }
            {
                var r = ret.As<global::Result1>();
                if (r != (global::Result1) 0)
                {
                    return ret;
                }
            }
            {
                var r = ret.As<global::WellKnownResult>();
                if (r != (global::WellKnownResult) 0)
                {
                    return ret;
                }
            }
            return new(global::ResultBase.None);
        }
        public static readonly global::System.Collections.Immutable.ImmutableArray<global::ResultSet> ResultSets = [
            global::ResultBase.ResultSetOf<global::Result1>([global::Result1.Hello, global::Result1.World]),
            global::ResultBase.ResultSetOf<global::WellKnownResult>([global::WellKnownResult.GenericFailure]),
        ];
        public static void Declare()
        {
            global::ResultBase.Declare<global::Result1>();
            global::ResultBase.Declare<global::WellKnownResult>();
        }
        public readonly global::Result1 AsResult1()
        {
            return Value.As<global::Result1>();
        }

        public readonly global::WellKnownResult AsWellKnown()
        {
            return Value.As<global::WellKnownResult>();
        }

        public readonly T As<T>() where T : struct
        {
            if (typeof(T) == typeof(global::Result1))
            {
                return (T) (object) AsResult1();
            }
            if (typeof(T) == typeof(global::WellKnownResult))
            {
                return (T) (object) AsWellKnown();
            }
            throw new global::System.InvalidOperationException($"Type {typeof(T).FullName!} is not allowed here");
        }

        public readonly bool IsOk
        {
            get
            {
                {
                    var r = As<global::Result1>();
                    if (r != (global::Result1) 0)
                    {
                        if (r == global::Result1.Hello)
                        {
                            return true;
                        }
                        if (r == global::Result1.World)
                        {
                            return true;
                        }
                    }
                }
                return false;
            }
        }
    }
}
partial class Helper0
{
    [global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Auto)]
    public partial record struct ResultPayload
    {
    }
}
