//HintName: MyResult.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
using ResultTypes.Shared;
using System;
public partial record struct MyResult
{
    public required MyResultTag Tag { get; init; }
    public global::System.Exception? Exception { get; init; }
    public MyResultPayload Payload;
    public static MyResult Ok(MyOtherResult otherResult)
    {
        global::System.Diagnostics.Debug.Assert(otherResult.Tag.IsOk, "Check IsOk before constructing the result");
        return new()
        {
            Tag = new(otherResult.Tag),
            Payload = new()
            {
                MyOtherResult = otherResult.Payload,
            },
            Exception = otherResult.Exception,
        };
    }
}
public partial record struct MyResultTag
{
    public global::ResultBase Value { get; }
    public readonly bool IsNone => Value.IsNone;
    private MyResultTag(global::ResultBase tag) => Value = tag;
    public MyResultTag(MyOtherResultTag tag)
    {
        Value = tag.Value;
    }

    public static MyResultTag TryCreateWithCheck(global::ResultBase value)
    {
        var ret = new MyResultTag(value);
        if (value.IsNone)
        {
            return ret;
        }
        {
            var r = ret.As<MyOtherResultTag>();
            if (!r.IsNone)
            {
                return ret;
            }
        }
        return new(global::ResultBase.None);
    }
    public static readonly global::System.Collections.Immutable.ImmutableArray<global::ResultSet> ResultSets = [
        .. MyOtherResultTag.ResultSets,
    ];
    public static void Declare()
    {
        MyOtherResultTag.Declare();
    }
    public readonly MyOtherResultTag AsMyOtherResultTag()
    {
        return MyOtherResultTag.TryCreateWithCheck(Value);
    }

    public readonly T As<T>() where T : struct
    {
        if (typeof(T) == typeof(MyOtherResultTag))
        {
            return (T) (object) AsMyOtherResultTag();
        }
        throw new global::System.InvalidOperationException($"Type {typeof(T).FullName!} is not allowed here");
    }

    public readonly bool IsOk
    {
        get
        {
            return false;
        }
    }
}
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Auto)]
partial struct MyResultPayload
{
    public MyOtherResultPayload MyOtherResult;
}