//HintName: Hello.CachedPropertyInfo.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
public static class HelloProps
{
    public static readonly global::PropertyCacheHelper.Shared.CachedPropertyInfo<global::Hello, int> Id = new(x => x.Id);
}
