//HintName: Result1.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
public partial record struct Result1
{
    public required Result1Tag Tag { get; init; }
    public global::System.Exception? Exception { get; init; }
    public static Result1 Ok()
    {
        var tag = global::WellKnownResult.Ok;
        return new()
        {
            Tag = new(tag),
        };
    }

}
public record struct Result1Tag
{
    public ResultBase Value { get; }
    public readonly bool IsNone => Value.IsNone;
    private Result1Tag(ResultBase tag) => Value = tag;
    public Result1Tag(global::WellKnownResult tag)
    {
        global::System.Diagnostics.Debug.Assert(tag is global::WellKnownResult.Ok);
        Value = ResultBase.Create<global::WellKnownResult>(tag);
    }

    public static Result1Tag TryCreateWithCheck(ResultBase value)
    {
        var ret = new Result1Tag(value);
        if (value.IsNone)
        {
            return ret;
        }
        {
            var r = ret.As<global::WellKnownResult>();
            if (r != (global::WellKnownResult) 0)
            {
                return ret;
            }
        }
        return new(ResultBase.None);
    }
    public static readonly global::System.Collections.Immutable.ImmutableArray<global::ResultSet> ResultSets = [
        ResultBase.ResultSetOf<global::WellKnownResult>([global::WellKnownResult.Ok]),
    ];
    public static void Declare()
    {
        ResultBase.Declare<global::WellKnownResult>();
    }
    public readonly global::WellKnownResult AsWellKnown()
    {
        return ResultBase.As<global::WellKnownResult>(Value);
    }

    public readonly T As<T>() where T : struct
    {
        if (typeof(T) == typeof(global::WellKnownResult))
        {
            return (T) (object) AsWellKnown();
        }
        throw new global::System.InvalidOperationException($"Type {typeof(T).FullName!} is not allowed here");
    }

    public readonly bool IsOk
    {
        get
        {
            {
                var r = As<global::WellKnownResult>();
                if (r != (global::WellKnownResult) 0)
                {
                    if (r == global::WellKnownResult.Ok)
                    {
                        return true;
                    }
                }
            }
            return false;
        }
    }
}
