//HintName: MyResult1.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
using ResultTypes.Shared;
using System;
public partial record struct MyResult1
{
    public required MyResult1Tag Tag { get; init; }
    public global::System.Exception? Exception { get; init; }
    public MyResult1Payload Payload => new();
    public static MyResult1 Failure(global::System.Exception? exception = null)
    {
        var tag = global::WellKnownResult.GenericFailure;
        return new()
        {
            Tag = new(tag),
            Exception = exception,
        };
    }

}
public partial record struct MyResult1Tag
{
    public global::ResultBase Value { get; }
    public readonly bool IsNone => Value.IsNone;
    private MyResult1Tag(global::ResultBase tag) => Value = tag;
    public MyResult1Tag(global::WellKnownResult tag)
    {
        global::System.Diagnostics.Debug.Assert(tag is global::WellKnownResult.GenericFailure);
        Value = global::ResultBase.Create<global::WellKnownResult>(tag);
    }

    public static MyResult1Tag TryCreateWithCheck(global::ResultBase value)
    {
        var ret = new MyResult1Tag(value);
        if (value.IsNone)
        {
            return ret;
        }
        {
            var r = ret.As<global::WellKnownResult>();
            if (r != (global::WellKnownResult) 0)
            {
                return ret;
            }
        }
        return new(global::ResultBase.None);
    }
    public static readonly global::System.Collections.Immutable.ImmutableArray<global::ResultSet> ResultSets = [
        global::ResultBase.ResultSetOf<global::WellKnownResult>([global::WellKnownResult.GenericFailure]),
    ];
    public static void Declare()
    {
        global::ResultBase.Declare<global::WellKnownResult>();
    }
    public readonly global::WellKnownResult AsWellKnown()
    {
        return Value.As<global::WellKnownResult>();
    }

    public readonly T As<T>() where T : struct
    {
        if (typeof(T) == typeof(global::WellKnownResult))
        {
            return (T) (object) AsWellKnown();
        }
        throw new global::System.InvalidOperationException($"Type {typeof(T).FullName!} is not allowed here");
    }

    public readonly bool IsOk
    {
        get
        {
            return false;
        }
    }
}
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Auto)]
public partial record struct MyResult1Payload
{
}