//HintName: MyResult.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
using ResultTypes.Shared;
using System;
public partial record struct MyResult
{
    public required MyResultTag Tag { get; init; }
    public global::System.Exception? Exception { get; init; }
    public MyResultPayload Payload;
    public static MyResult Ok(global::Tag1 tag, global::PayloadA payload)
    {
        global::System.Diagnostics.Debug.Assert(tag is global::Tag1.A);
        return new()
        {
            Tag = new(tag),
            Payload = new()
            {
                PayloadA = payload,
            },
        };
    }

    public static MyResult Failure(global::Tag2 tag, global::PayloadA payload, global::System.Exception? exception = null)
    {
        global::System.Diagnostics.Debug.Assert(tag is global::Tag2.C);
        return new()
        {
            Tag = new(tag),
            Payload = new()
            {
                PayloadA = payload,
            },
            Exception = exception,
        };
    }

}
public partial record struct MyResultTag
{
    public global::ResultBase Value { get; }
    public readonly bool IsNone => Value.IsNone;
    private MyResultTag(global::ResultBase tag) => Value = tag;
    public MyResultTag(global::Tag1 tag)
    {
        global::System.Diagnostics.Debug.Assert(tag is global::Tag1.A);
        Value = global::ResultBase.Create<global::Tag1>(tag);
    }

    public MyResultTag(global::Tag2 tag)
    {
        global::System.Diagnostics.Debug.Assert(tag is global::Tag2.C);
        Value = global::ResultBase.Create<global::Tag2>(tag);
    }

    public static MyResultTag TryCreateWithCheck(global::ResultBase value)
    {
        var ret = new MyResultTag(value);
        if (value.IsNone)
        {
            return ret;
        }
        {
            var r = ret.As<global::Tag1>();
            if (r != (global::Tag1) 0)
            {
                return ret;
            }
        }
        {
            var r = ret.As<global::Tag2>();
            if (r != (global::Tag2) 0)
            {
                return ret;
            }
        }
        return new(global::ResultBase.None);
    }
    public static readonly global::System.Collections.Immutable.ImmutableArray<global::ResultSet> ResultSets = [
        global::ResultBase.ResultSetOf<global::Tag1>([global::Tag1.A]),
        global::ResultBase.ResultSetOf<global::Tag2>([global::Tag2.C]),
    ];
    public static void Declare()
    {
        global::ResultBase.Declare<global::Tag1>();
        global::ResultBase.Declare<global::Tag2>();
    }
    public readonly global::Tag1 AsTag1()
    {
        return Value.As<global::Tag1>();
    }

    public readonly global::Tag2 AsTag2()
    {
        return Value.As<global::Tag2>();
    }

    public readonly T As<T>() where T : struct
    {
        if (typeof(T) == typeof(global::Tag1))
        {
            return (T) (object) AsTag1();
        }
        if (typeof(T) == typeof(global::Tag2))
        {
            return (T) (object) AsTag2();
        }
        throw new global::System.InvalidOperationException($"Type {typeof(T).FullName!} is not allowed here");
    }

    public readonly bool IsOk
    {
        get
        {
            {
                var r = As<global::Tag1>();
                if (r != (global::Tag1) 0)
                {
                    if (r == global::Tag1.A)
                    {
                        return true;
                    }
                }
            }
            return false;
        }
    }
}
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Auto)]
public partial record struct MyResultPayload
{
    public global::PayloadA PayloadA;
}