//HintName: MyResult.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
using ResultTypes.Shared;
using System;
public partial record struct MyResult
{
    public required MyResultTag Tag { get; init; }
    public global::System.Exception? Exception { get; init; }
    public MyResultPayload Payload => new();
    public static MyResult Failure(global::MyResult1Tag tag, global::System.Exception? exception = null)
    {
        return new()
        {
            Tag = new(tag),
            Exception = exception,
        };
    }

}
public partial record struct MyResultTag
{
    public global::ResultBase Value { get; }
    public readonly bool IsNone => Value.IsNone;
    private MyResultTag(global::ResultBase tag) => Value = tag;
    public MyResultTag(global::MyResult1Tag tag)
    {
        Value = tag.Value;
    }

    public static MyResultTag TryCreateWithCheck(global::ResultBase value)
    {
        var ret = new MyResultTag(value);
        if (value.IsNone)
        {
            return ret;
        }
        {
            var r = ret.As<global::MyResult1Tag>();
            if (!r.IsNone)
            {
                return ret;
            }
        }
        return new(global::ResultBase.None);
    }
    public static readonly global::System.Collections.Immutable.ImmutableArray<global::ResultSet> ResultSets = [
        .. global::MyResult1Tag.ResultSets,
    ];
    public static void Declare()
    {
        global::MyResult1Tag.Declare();
    }
    public readonly global::MyResult1Tag AsMyResult1Tag()
    {
        return global::MyResult1Tag.TryCreateWithCheck(Value);
    }

    public readonly T As<T>() where T : struct
    {
        if (typeof(T) == typeof(global::MyResult1Tag))
        {
            return (T) (object) AsMyResult1Tag();
        }
        throw new global::System.InvalidOperationException($"Type {typeof(T).FullName!} is not allowed here");
    }

    public readonly bool IsOk
    {
        get
        {
            return false;
        }
    }
}
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Auto)]
public partial record struct MyResultPayload
{
}
