//HintName: OtherDerived.CachedPropertyInfo.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
public static class OtherDerivedProps
{
    public static readonly global::PropertyCacheHelper.Shared.CachedPropertyInfo<global::OtherDerived, int> IdDerived = new(x => x.IdDerived);
}
