//HintName: Base.CachedPropertyInfo.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
public static class BaseProps
{
    public static readonly global::PropertyCacheHelper.Shared.CachedPropertyInfo<global::Base, int> Id = new(x => x.Id);
}
